window.TMDB_CONFIG = {
  READ_ACCESS_TOKEN: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJlZTBjODEwMzg3MTRiZjU1YzMwNDFmODZmNGUwMTAxMiIsIm5iZiI6MTc2MjUyOTMyNS44NzksInN1YiI6IjY5MGUxMDJkNmYzMzQ2NzY4M2MwNTA4ZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Sfio3YC9_WOIzwxW1ARsU2F6ENJsou282L5Isv18XoQ',
  LANGUAGE: 'en-US',
  IMAGE_BASE: 'https://image.tmdb.org/t/p/'
};
